### ISSUE TITLE
expired certificate

### ISSUE THREAD

**Issue by ddavila0** [paulmillar/http-tpc-utils#15]
The host certificate used for the third-party unauthenticated pulls is expired:
* Server certificate:
* 	subject: CN=prometheus.desy.de,OU=DESY,O=GermanGrid,C=DE
* 	start date: Nov 28 14:47:24 2018 GMT
* 	expire date: Dec 28 14:47:24 2019 GMT
* 	common name: prometheus.desy.de
* 	issuer: CN=GridKa-CA,O=GermanGrid,C=DE
* NSS error -8181 (SEC_ERROR_EXPIRED_CERTIFICATE)
* Peer's Certificate has expired.

**Comment by paulmillar** [comment]
Thanks for reporting this.

I've suspended the HTTP third-party transfer testing until the new certificate is installed.

**Comment by paulmillar** [comment]
The new certificate is installed, so the problem should now be fixed.

Thanks again for reporting this.

**Comment by ddavila0** [comment]
thank you so much!
